### ISSUE TITLE
QA形式分享

### ISSUE THREAD

**Issue by bifeng** [Dikea/ML-Weekly-Learning#1]
提个建议。当前比较难理解的地方，以提问形式，既可以自己回答，也可以方便他人解答。Summary部分主要总结心得。
```
Question:
Anwser:
```
```
Summary:
```

**Comment by Dikea** [comment]
不错的，这样学习能够更加深入一些，我们考虑一下，看看是否采用这种方式。

**Comment by Light--** [comment]
想知道怎么通过私人邀请方式参加CV打卡。。。。
